In [20]:
import numpy as np
import pandas as pd

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

In [21]:
# Load the dataset
data = pd.read_csv('../../data/auto-mpg.csv')
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [22]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    str
dtypes: float64(3), int64(4), str(2)
memory usage: 28.1 KB

In [23]:
# Cleaning the dataset
data['horsepower'] = pd.to_numeric(data['horsepower'], errors='coerce')
df_clean = (
    data.drop(columns=['origin', 'car name']) # Drop non-numeric columns
    .rename(columns={'model year': 'model_year'})
    .dropna()
    .reset_index(drop=True) # Reset index after dropping rows
)

df_clean.head()

    mpg  cylinders  displacement  horsepower  weight  acceleration  model_year
0  18.0          8         307.0       130.0    3504          12.0          70
1  15.0          8         350.0       165.0    3693          11.5          70
2  18.0          8         318.0       150.0    3436          11.0          70
3  16.0          8         304.0       150.0    3433          12.0          70
4  17.0          8         302.0       140.0    3449          10.5          70

In [24]:
df_clean.columns.tolist()

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model_year']

In [25]:
TARGET = 'mpg'
quan_categories = ['displacement', 'horsepower', 'weight', 'acceleration', 'model_year']

In [26]:
df_clean[TARGET].describe()

count    392.000000
mean      23.445918
std        7.805007
min        9.000000
25%       17.000000
50%       22.750000
75%       29.000000
max       46.600000
Name: mpg, dtype: float64

In [27]:
df_clean[quan_categories].describe()

       displacement  horsepower       weight  acceleration  model_year
count    392.000000  392.000000   392.000000    392.000000  392.000000
mean     194.411990  104.469388  2977.584184     15.541327   75.979592
std      104.644004   38.491160   849.402560      2.758864    3.683737
min       68.000000   46.000000  1613.000000      8.000000   70.000000
25%      105.000000   75.000000  2225.250000     13.775000   73.000000
50%      151.000000   93.500000  2803.500000     15.500000   76.000000
75%      275.750000  126.000000  3614.750000     17.025000   79.000000
max      455.000000  230.000000  5140.000000     24.800000   82.000000