In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler

# Loss function definitions
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

# Configs
sns.set_theme(style="whitegrid")
plt.rcParams['figure.dpi'] = 110

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

In [15]:
# Load the dataset
data = pd.read_csv('data/auto-mpg.csv')
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [16]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    str
dtypes: float64(3), int64(4), str(2)
memory usage: 28.1 KB

In [17]:
# Cleaning the dataset
df_clean = (
    data.drop(columns=['origin', 'car name']) # Drop non-numeric columns
    .rename(columns={'model year': 'model_year'})
    .dropna()
    .reset_index(drop=True) # Reset index after dropping rows
)

df_clean.head()

    mpg  cylinders  displacement horsepower  weight  acceleration  model_year
0  18.0          8         307.0        130    3504          12.0          70
1  15.0          8         350.0        165    3693          11.5          70
2  18.0          8         318.0        150    3436          11.0          70
3  16.0          8         304.0        150    3433          12.0          70
4  17.0          8         302.0        140    3449          10.5          70

In [18]:
df_clean.columns.tolist()

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model_year']

In [19]:
TARGET = 'mpg'
quan_categories = ['displacement', 'horsepower', 'weight', 'acceleration', 'model_year']

In [20]:
df_clean[TARGET].describe()

count    398.000000
mean      23.514573
std        7.815984
min        9.000000
25%       17.500000
50%       23.000000
75%       29.000000
max       46.600000
Name: mpg, dtype: float64

In [21]:
df_clean[quan_categories].describe()

       displacement       weight  acceleration  model_year
count    398.000000   398.000000    398.000000  398.000000
mean     193.425879  2970.424623     15.568090   76.010050
std      104.269838   846.841774      2.757689    3.697627
min       68.000000  1613.000000      8.000000   70.000000
25%      104.250000  2223.750000     13.825000   73.000000
50%      148.500000  2803.500000     15.500000   76.000000
75%      262.000000  3608.000000     17.175000   79.000000
max      455.000000  5140.000000     24.800000   82.000000